---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-new
  labels:
    app: website-new
spec:
  selector:
    matchLabels:
      app: website-new
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: website-new
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - K8S_Server_Node
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: website-new
        image: ravikiranmn/website-new
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "150m"
          limits:
            memory: "256Mi"
            cpu: "500m"   
