apiVersion: apps/v1
kind: Deployment
metadata:
  name: webpage-deployment
  labels:
    app: webpage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webpage
  template:
    metadata:
      labels:
        app: webpage
    spec:
      containers:
      - name: ravikiranmn
        image: ravikiranmn/website-develop
        ports:
        - containerPort: 80
